# Generated by Django 4.1.4 on 2023-02-12 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orders_address_alter_orders_expected_deliverydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='dicount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 2, 17)),
        ),
    ]
