# Generated by Django 4.1.4 on 2023-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_dicount_offers_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
